### ISSUE TITLE
En tant que restaurateur, je veux ajouter des repas.

### ISSUE THREAD

**Issue by Gadiffet** [SVT-Cube-Project/cube--backend#144]
- [x] Front
- [x] Back
- [x] Integration

**Comment by Gadiffet** [comment]
@valou59553 Impossible d'envoyer une image quand je crée un "Meal".

Car il attend un string (URL), alors que je lui envoie un fichier ".png"

**Comment by valou59553** [comment]
bizarre pourtant cest ok ici @Gadiffet 

![Image](https://github.com/CESI-Project/cube--backend/assets/73795307/364628b9-f92c-49de-ad42-b0dae70cfa39)

**Comment by Gadiffet** [comment]
Oui ma faute :/
