### ISSUE TITLE
As Front-Dev, I want to use only one request to get informations

### ISSUE THREAD

**Issue by Gadiffet** [SVT-Cube-Project/cube--backend#99]
- [x] Edit `api/v1/topic/{id}` to get all this information : 
    - [x] Get Topic (NAme, Text, .. etc)
    - [x] Get Views
    - [ ] Get Favorites : ( pas une bonne idée , personnel à chacun )
    - [x] Get Comment
    - [x] Get SubComment

- [x] Create `api/v1/user/{id}/_dashboard` to get all this information : 
    - [x] Get TopicByUser
    - [x] Get TotalViews
    - [x] Get TotalUser
    - [x] Get TotalTopics
    - [x] Get TotalTopicsByCategories
    - [x] Get TotalCategories
    - [x] Get TotalTopicsViews (Nbr total de toutes les vues cumulé)
    - [x] Get TotalComment
    - [x] Get TotalSubComment
    - [x] Get AverageCommentByTopics
    - [x] Get AverageSubCommentByComment

**Comment by Gadiffet** [comment]
Front Topic Done

**Comment by Gadiffet** [comment]
Error 406

**Comment by valou59553** [comment]
cest corrrigé
